name: CI - Lint, Unit & E2E

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Unit Tests (Jest)
        run: npm test

  e2e:
    needs: lint-and-unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install deps
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Start static server
        run: |
          npm run start &
          echo "Waiting for server..."
          npx wait-on http://localhost:8080
      - name: Run Playwright E2E
        run: npx playwright test --project=chromium --reporter=list